Feature/has geometry
maykinmedia/objecttypes-api pull request #72
Opened 2021-11-22 15:18 UTC by annashamray

issue - https://github.com/maykinmedia/objects-api/issues/263

2021-11-25 15:09 UTC, joeribekker requested changes
Hmm, it feels a little brittle. Can you still create objects with geo in the objects API even if hasGeo is false in the objecttype?

This should be checked! And, we should document in the API spec what happens if you set hasGeo to true/false, and also document it in the objects api that creating an object can error because of it.

2021-11-26 16:40 UTC, annashamray commented
@joeribekker I've updated the description of the field in the schema
And I also created the check in the Objects API, which prevents adding geometry if the related objecttype doesn't allow it -  https://github.com/maykinmedia/objects-api/pull/265

2021-12-03 11:29 UTC, annashamray commented
as discussed with @joeribekker `hasGeometry` field was renamed to `canHaveGeometry`

2021-12-03 15:25 UTC, joeribekker approved these changes

2021-12-03 16:12 UTC, merged